export const SITE_LANGS = ["zh", "en", "ru"] as const;

export type SiteLang = (typeof SITE_LANGS)[number];
export type PageKey = "home" | "services" | "routes" | "industries" | "platform" | "about" | "contact";
export type NavKey = PageKey | "news";

export const SITE_NAV: Record<SiteLang, Record<NavKey, string>> = {
  zh: {
    home: "首页",
    services: "服务",
    routes: "路线",
    industries: "行业",
    platform: "平台",
    news: "动态",
    about: "关于",
    contact: "联系",
  },
  en: {
    home: "Home",
    services: "Services",
    routes: "Routes",
    industries: "Industries",
    platform: "Platform",
    news: "News",
    about: "About",
    contact: "Contact",
  },
  ru: {
    home: "Главная",
    services: "Сервисы",
    routes: "Маршруты",
    industries: "Отрасли",
    platform: "Платформа",
    news: "Новости",
    about: "О нас",
    contact: "Контакты",
  },
};

export const NAV_LINKS: Array<{ key: NavKey; href: string }> = [
  { key: "home", href: "/" },
  { key: "services", href: "/services/" },
  { key: "routes", href: "/routes/" },
  { key: "industries", href: "/industries/" },
  { key: "platform", href: "/platform/" },
  { key: "news", href: "/news/" },
  { key: "about", href: "/about/" },
  { key: "contact", href: "/contact/" },
];

export const TRUST_NARRATIVE: Record<SiteLang, { title: string; text: string; items: Array<{ value: string; label: string; note: string }> }> = {
  zh: {
    title: "年轻的在地公司，不从零开始",
    text: "HPF.kz 扎根哈萨克斯坦一年有余，依托中国上市公司体系的治理、供应链与资产能力，把集团资源转化为中亚现场可执行的服务。",
    items: [
      { value: "上市体系", label: "中国母体背书", note: "治理标准、供应链资源与长期经营能力" },
      { value: "182 台", label: "集团车队资源", note: "Volvo / Scania 干线运力" },
      { value: "5 台", label: "哈国本地车辆", note: "Sitrak 笼车与本地调度" },
      { value: "仓配资产", label: "阿拉木图履约", note: "仓储、分拨、贴标与逆向处理" },
    ],
  },
  en: {
    title: "A young local company that did not start from zero",
    text: "HPF.kz has operated in Kazakhstan for just over a year, backed by the governance, supply-chain resources and asset capability of a Chinese listed-company group.",
    items: [
      { value: "Listed group", label: "China-backed foundation", note: "Governance, supply-chain resources and long-term capacity" },
      { value: "182 units", label: "Group fleet resources", note: "Volvo / Scania linehaul capacity" },
      { value: "5 units", label: "Kazakhstan fleet", note: "Sitrak cage trucks and local dispatch" },
      { value: "Warehousing", label: "Almaty fulfilment", note: "Storage, distribution, labelling and returns" },
    ],
  },
  ru: {
    title: "Молодая местная компания с сильной основой",
    text: "HPF.kz работает в Казахстане чуть больше года и опирается на стандарты управления, ресурсы цепочки поставок и активы группы китайской публичной компании.",
    items: [
      { value: "Публичная группа", label: "Основа из Китая", note: "Управление, ресурсы и долгосрочные возможности" },
      { value: "182 ед.", label: "Ресурсы парка группы", note: "Магистральные Volvo / Scania" },
      { value: "5 ед.", label: "Парк Казахстана", note: "Фургоны Sitrak и локальная диспетчеризация" },
      { value: "Склад", label: "Исполнение в Алматы", note: "Хранение, дистрибуция, маркировка и возвраты" },
    ],
  },
};

const routeImage =
  "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1800&q=80";
const warehouseImage =
  "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=1800&q=80";
const railImage =
  "https://images.unsplash.com/photo-1532105956626-9569c03602f6?auto=format&fit=crop&w=1800&q=80";

type LocalPage = {
  metaTitle: string;
  metaDescription: string;
  kicker: string;
  title: string;
  lead: string;
  primaryAction: string;
  secondaryAction: string;
  visualLabel: string;
  stats: Array<{ value: string; label: string }>;
  sectionsTitle: string;
  sections: Array<{ title: string; text: string; bullets: string[] }>;
  panelsTitle: string;
  panels: Array<{ label: string; title: string; text: string; points: string[] }>;
  timelineTitle: string;
  timeline: Array<{ step: string; title: string; text: string }>;
  ctaTitle: string;
  ctaText: string;
  ctaButton: string;
};

type PageSet = Record<SiteLang, LocalPage> & {
  image: string;
  imageAlt: Record<SiteLang, string>;
};

export const SITE_PAGES: Record<PageKey, PageSet> = {
  home: {
    image: routeImage,
    imageAlt: {
      zh: "集装箱与跨境物流运营场景",
      en: "Container logistics operation",
      ru: "Контейнерная логистика",
    },
    zh: {
      metaTitle: "HPF.kz | 中哈欧跨境物流确定性交付平台",
      metaDescription: "HPF.kz 为中国贸易商、哈萨克斯坦本地客户和欧洲收货方提供跨境物流、清关、仓储、路线和平台化运营服务。",
      kicker: "HPF.kz / Kazakhstan logistics control tower",
      title: "把中国制造，稳稳送入中亚",
      lead: "依托中国上市公司体系的治理与供应链资产，HPF.kz 在哈萨克斯坦把路线、清关、仓储、车队和末端交付组织成一条可见、可控、可复盘的履约链。",
      primaryAction: "配置路线",
      secondaryAction: "查看服务",
      visualLabel: "China - Kazakhstan - Europe",
      stats: [
        { value: "10-12天", label: "中间走廊目标时效" },
        { value: "4段", label: "主路线风险分层" },
        { value: "3语", label: "中英俄协同" },
        { value: "T+0", label: "异常响应机制" },
      ],
      sectionsTitle: "客户决策入口",
      sections: [
        {
          title: "服务不是菜单，是可组合的交付模块",
          text: "客户不需要听一堆物流名词。客户需要知道这票货从哪里走、文件谁负责、库存放哪里、异常谁处理。",
          bullets: ["清关合规", "仓储分拨", "跨境 TIR", "末端交付"],
        },
        {
          title: "跨境 TIR 是产品，不只是运输方式",
          text: "依托集团 Volvo 与 Scania 车辆资源、行业第一梯队 182 台车队，以及哈萨克斯坦 5 台汕德卡笼车，把中哈欧公路段做成可调度的产品能力。",
          bullets: ["Volvo/Scania", "182 台车队", "5 台汕德卡笼车", "TIR 公路"],
        },
        {
          title: "路线不是地图，是承诺边界",
          text: "中哈欧链路有港口、铁路、公路、转关和收货预约。我们把每段风险拆开，先定义边界，再承诺时效。",
          bullets: ["中国集货", "阿拉木图枢纽", "库雷克港", "欧洲交付"],
        },
        {
          title: "平台不是噱头，是运营台账",
          text: "报价、文件、节点、库存和复盘报告必须沉淀为客户能看见的数据，而不是停留在聊天记录里。",
          bullets: ["路线报价", "文件中台", "节点追踪", "复盘报告"],
        },
      ],
      panelsTitle: "按业务场景查看方案",
      panels: [
        {
          label: "服务",
          title: "一票到底的责任边界",
          text: "从工厂取货到签收回单，按货类、时效和预算拆成可执行模块。",
          points: ["EAEU 文件预审", "阿拉木图仓配", "跨境 TIR", "POD 与异常报告"],
        },
        {
          label: "TIR车队",
          title: "把跨境 TIR 做成可调度产品",
          text: "集团 Volvo 与 Scania 车辆资源、182 台行业第一梯队车队，以及哈萨克斯坦 5 台汕德卡笼车，支撑中哈欧公路段稳定执行。",
          points: ["Volvo/Scania", "182 台车队", "5 台汕德卡笼车", "TIR 公路"],
        },
        {
          label: "路线",
          title: "主路线和备用路线同时设计",
          text: "不是只给最低价，而是给可执行的路线组合和节点风险。",
          points: ["中国出口", "哈萨克斯坦入境", "库雷克装船", "欧洲预约交付"],
        },
        {
          label: "平台",
          title: "客户看得到执行状态",
          text: "把物流经验变成一张运营视图，减少反复追问和信息断层。",
          points: ["状态追踪", "资料留痕", "费用偏差", "时效复盘"],
        },
      ],
      timelineTitle: "一票货的执行路径",
      timeline: [
        { step: "01", title: "诊断", text: "确认货类、目的地、合规要求、时效边界和预算。" },
        { step: "02", title: "配置", text: "生成主路线、备用路线、清关方案、仓储节点和 SLA。" },
        { step: "03", title: "执行", text: "推进取货、出口、入境、转运、仓配和签收。" },
        { step: "04", title: "复盘", text: "输出异常、费用、时效和文件完整性报告。" },
      ],
      ctaTitle: "把下一票货先变成路线图",
      ctaText: "提供货类、起运地、目的地、重量体积和期望到达时间，我们返回可执行方案。",
      ctaButton: "发送路线需求",
    },
    en: {
      metaTitle: "HPF.kz | China-Kazakhstan-Europe logistics control platform",
      metaDescription: "HPF.kz provides cross-border logistics, customs, warehousing, routing and operating systems for Chinese traders, Kazakhstan clients and European consignees.",
      kicker: "HPF.kz / Kazakhstan logistics control tower",
      title: "Built in China. Delivered across Central Asia.",
      lead: "Backed by the governance and supply-chain assets of a Chinese listed-company group, HPF.kz turns routes, customs, warehousing, fleet and final delivery into one visible operating chain in Kazakhstan.",
      primaryAction: "Configure route",
      secondaryAction: "View services",
      visualLabel: "China - Kazakhstan - Europe",
      stats: [
        { value: "10-12d", label: "Middle Corridor target" },
        { value: "4 legs", label: "risk-layered route" },
        { value: "3 langs", label: "ZH/EN/RU operations" },
        { value: "T+0", label: "exception response" },
      ],
      sectionsTitle: "Decision entrances for customers",
      sections: [
        { title: "Services are operating modules", text: "Customers need to know the route, document owner, inventory point and exception owner.", bullets: ["Customs", "Warehousing", "Cross-border TIR", "Final delivery"] },
        { title: "Cross-border TIR is a product", text: "Group Volvo and Scania vehicle resources, an industry-leading 182-unit fleet and 5 Sitrak cage trucks in Kazakhstan make the China-Kazakhstan-Europe road leg schedulable.", bullets: ["Volvo/Scania", "182-unit fleet", "5 Sitrak cage trucks", "TIR road"] },
        { title: "Routes define the promise boundary", text: "Ports, rail, road, transit customs and delivery appointment risks are separated before time is promised.", bullets: ["China origin", "Almaty hub", "Kuryk port", "Europe delivery"] },
        { title: "The platform is the operating ledger", text: "Quotes, documents, milestones, inventory and review reports should be visible data, not scattered messages.", bullets: ["Route quotes", "Document center", "Tracking", "Review reports"] },
      ],
      panelsTitle: "Explore solutions by operating scenario",
      panels: [
        { label: "Services", title: "One accountable shipment boundary", text: "From factory pickup to POD, modules are configured by cargo, time and budget.", points: ["EAEU file review", "Almaty fulfillment", "Cross-border TIR", "POD and exception report"] },
        { label: "TIR fleet", title: "Cross-border TIR as a product", text: "With Group Volvo and Scania resources, an industry-leading 182-unit fleet and 5 Sitrak cage trucks in Kazakhstan, the road leg becomes schedulable capacity.", points: ["Volvo/Scania", "182-unit fleet", "5 Sitrak cage trucks", "TIR road"] },
        { label: "Routes", title: "Primary and fallback routes together", text: "Not the cheapest line only, but an executable route portfolio with node risk.", points: ["China export", "Kazakhstan import", "Kuryk loading", "Europe appointment"] },
        { label: "Platform", title: "Execution status is visible", text: "Operational knowledge becomes a control view that reduces repeated follow-up.", points: ["Status tracking", "Document trail", "Cost variance", "Transit review"] },
      ],
      timelineTitle: "Shipment execution path",
      timeline: [
        { step: "01", title: "Diagnose", text: "Cargo type, destination, compliance, time boundary and budget." },
        { step: "02", title: "Configure", text: "Primary route, fallback route, customs plan, warehouse node and SLA." },
        { step: "03", title: "Execute", text: "Pickup, export, import, transfer, fulfillment and POD." },
        { step: "04", title: "Review", text: "Exception, cost, transit time and document integrity report." },
      ],
      ctaTitle: "Turn the next shipment into a route map",
      ctaText: "Share cargo type, origin, destination, weight/volume and target arrival. We return an executable plan.",
      ctaButton: "Send route request",
    },
    ru: {
      metaTitle: "HPF.kz | Логистическая платформа Китай-Казахстан-Европа",
      metaDescription: "HPF.kz предоставляет трансграничную логистику, таможню, склад, маршруты и операционную платформу для Китая, Казахстана и Европы.",
      kicker: "HPF.kz / логистический центр Казахстана",
      title: "Из Китая — в Центральную Азию. Надёжно.",
      lead: "Опираясь на управление и активы цепочки поставок группы китайской публичной компании, HPF.kz объединяет маршрут, таможню, склад, автопарк и доставку в единую операционную цепь в Казахстане.",
      primaryAction: "Настроить маршрут",
      secondaryAction: "Сервисы",
      visualLabel: "Китай - Казахстан - Европа",
      stats: [
        { value: "10-12д", label: "цель Среднего коридора" },
        { value: "4 этапа", label: "маршрут с рисками" },
        { value: "3 языка", label: "ZH/EN/RU операции" },
        { value: "T+0", label: "реакция на отклонения" },
      ],
      sectionsTitle: "Точки принятия решений для клиента",
      sections: [
        { title: "Сервисы как модули исполнения", text: "Клиенту важно знать маршрут, владельца документов, точку склада и владельца исключений.", bullets: ["Таможня", "Склад", "TIR авто", "Доставка"] },
        { title: "Трансграничный TIR как продукт", text: "Ресурсы группы Volvo и Scania, 182 единицы парка первого эшелона отрасли и 5 фургонов Sitrak в Казахстане делают автоплечо Китай-Казахстан-Европа планируемым.", bullets: ["Volvo/Scania", "182 единицы", "5 Sitrak фургонов", "TIR авто"] },
        { title: "Маршрут задает границы обещания", text: "Порт, ЖД, авто, транзит и запись получателя анализируются до обещания срока.", bullets: ["Китай", "Алматы", "Курык", "Европа"] },
        { title: "Платформа как журнал операций", text: "Ставки, документы, узлы, склад и отчеты становятся видимыми данными.", bullets: ["Расчет", "Документы", "Трекинг", "Отчеты"] },
      ],
      panelsTitle: "Решения по операционным сценариям",
      panels: [
        { label: "Сервисы", title: "Одна зона ответственности", text: "От забора до POD модули настраиваются по грузу, сроку и бюджету.", points: ["Проверка EAEU", "Склад Алматы", "Трансграничный TIR", "POD и отчет"] },
        { label: "TIR парк", title: "Трансграничный TIR как продукт", text: "Ресурсы группы Volvo и Scania, 182 единицы парка первого эшелона отрасли и 5 фургонов Sitrak в Казахстане превращают автоплечо в планируемую мощность.", points: ["Volvo/Scania", "182 единицы", "5 Sitrak фургонов", "TIR авто"] },
        { label: "Маршруты", title: "Основной и резервный маршрут", text: "Не только низкая ставка, а исполнимая маршрутная схема с рисками.", points: ["Экспорт Китай", "Импорт Казахстан", "Погрузка Курык", "Запись Европа"] },
        { label: "Платформа", title: "Статус исполнения виден", text: "Операционный опыт превращается в панель контроля.", points: ["Статусы", "Документы", "Отклонение затрат", "Анализ сроков"] },
      ],
      timelineTitle: "Путь исполнения груза",
      timeline: [
        { step: "01", title: "Диагностика", text: "Тип груза, назначение, комплаенс, срок и бюджет." },
        { step: "02", title: "Конфигурация", text: "Основной маршрут, резерв, таможня, склад и SLA." },
        { step: "03", title: "Исполнение", text: "Забор, экспорт, импорт, транзит, склад и POD." },
        { step: "04", title: "Анализ", text: "Исключения, стоимость, сроки и документы." },
      ],
      ctaTitle: "Превратим следующий груз в маршрутную карту",
      ctaText: "Укажите тип груза, отправление, назначение, вес/объем и срок. Мы вернем исполнимый план.",
      ctaButton: "Отправить запрос",
    },
  },
  services: {
    image: warehouseImage,
    imageAlt: { zh: "仓储和分拨作业", en: "Warehouse and distribution operation", ru: "Складская операция" },
    zh: {
      metaTitle: "清关与跨境物流服务 | HPF.kz",
      metaDescription: "HPF.kz 提供中国出口、哈萨克斯坦进口与转关协同，覆盖 HS 归类、文件预审、EAEU 证书、口岸查验，以及跨境 TIR、仓储分拨和本地交付。",
      kicker: "Customs & cross-border operations",
      title: "清关先行，运输随后。",
      lead: "从货物识别、HS 归类和贸易文件预审开始，衔接中国出口、哈萨克斯坦进口与转关节点，再把运输、仓储和末端交付接入同一条责任链。",
      primaryAction: "提交服务需求",
      secondaryAction: "查看路线",
      visualLabel: "Customs & operations",
      stats: [
        { value: "182台", label: "集团车队规模" },
        { value: "V+S", label: "Volvo/Scania 车辆" },
        { value: "5台", label: "哈萨克汕德卡笼车" },
        { value: "TIR", label: "跨境公路产品" },
      ],
      sectionsTitle: "清关与跨境履约能力",
      sections: [
        { title: "清关与 EAEU 合规", text: "发运前核对品名、用途、材质、品牌型号、HS 编码、申报要素、合同发票、装箱资料、证书与原产地文件；发运后衔接出口、进口、转关、补件与查验节点。", bullets: ["HS 归类", "货单证一致", "EAEU 证书", "口岸异常协同"] },
        { title: "跨境 TIR 车队服务", text: "以集团 Volvo 和 Scania 车辆为干线基础，结合行业第一梯队 182 台车队规模与哈萨克斯坦 5 台汕德卡笼车，服务中哈欧跨境公路运输。", bullets: ["TIR 公路", "Volvo/Scania", "182 台车队", "汕德卡笼车"] },
        { title: "中国企业出海服务", text: "面向中国企业进入哈萨克斯坦和欧洲市场，提供物流、清关、仓配、本地交付与运营落地协同。", bullets: ["出海物流", "本地履约", "清关合规", "仓配交付"] },
        { title: "库雷克绿通", text: "围绕跨里海节点做排期、港口协同、装船窗口和异常预警。", bullets: ["港口排期", "舱位协同", "节点预警", "到港复盘"] },
        { title: "仓储分拨", text: "阿拉木图仓配、贴标、分拣、轻加工、库存盘点和逆向处理。", bullets: ["SKU库存", "贴标分拣", "逆向揽收", "损益报告"] },
      ],
      panelsTitle: "清关责任链",
      panels: [
        { label: "清关", title: "先解决合规，再谈时效", text: "清关资料不完整，后面的承诺都会失真。我们不承诺“保证通关”，而是把可预见的问题前置，把现场问题明确到责任人。", points: ["贸易文件预审", "证书与监管要求", "税费与申报要素", "通关节点同步"] },
        { label: "TIR", title: "跨境 TIR 是可调度运力产品", text: "不是临时找车，而是用集团车队和哈萨克斯坦本地车辆把公路段变成可计划能力。", points: ["Volvo/Scania 干线", "182 台车队", "5 台汕德卡笼车", "TIR 节点协同"] },
        { label: "出海", title: "服务中国企业进入哈萨克与欧洲", text: "从第一票货到本地履约体系，帮助中国企业把物流、清关和交付能力落地。", points: ["路线诊断", "清关合规", "本地仓配", "交付复盘"] },
        { label: "仓配", title: "让库存状态进入运营台账", text: "仓储不是静态空间，而是交付节奏的一部分。", points: ["入库质检", "批次/SKU", "拣配出库", "逆向处理"] },
        { label: "干线", title: "多式联运降低单一路径风险", text: "铁路、公路、海运和空运按货类与时效组合。", points: ["铁路班列", "TIR 公路", "里海海运", "空运备选"] },
      ],
      timelineTitle: "一票货的清关工作次序",
      timeline: [
        { step: "01", title: "识别货物", text: "明确品名、用途、材质、型号、监管属性和贸易条款。" },
        { step: "02", title: "收口文件", text: "校核 HS 编码、申报要素、发票、箱单、证书与原产地资料。" },
        { step: "03", title: "衔接口岸", text: "同步出口、进口、转关、补件、改单和查验状态。" },
        { step: "04", title: "放行归档", text: "留存关键单证、节点结果与异常记录，完成本票复盘。" },
      ],
      ctaTitle: "先把货、单、证放到桌面上",
      ctaText: "发来品名、用途、材质、贸易条款、起止地和现有文件，我们先判断清关要求与资料缺口，再配置运输方案。",
      ctaButton: "咨询清关与运输",
    },
    en: {
      metaTitle: "Customs & cross-border logistics | HPF.kz",
      metaDescription: "HPF.kz coordinates China export, Kazakhstan import and transit customs, including HS classification, file review, EAEU certificates, border inspection, TIR transport, warehousing and local delivery.",
      kicker: "Customs & cross-border operations",
      title: "Customs first. Transport follows.",
      lead: "We start with cargo identification, HS classification and trade-file review, connect China export, Kazakhstan import and transit customs, then bring transport, warehousing and final delivery into the same accountable chain.",
      primaryAction: "Submit service need",
      secondaryAction: "View routes",
      visualLabel: "Customs & operations",
      stats: [
        { value: "182", label: "Group fleet units" },
        { value: "V+S", label: "Volvo/Scania fleet" },
        { value: "5", label: "KZ Sitrak cage trucks" },
        { value: "TIR", label: "cross-border road product" },
      ],
      sectionsTitle: "Customs and delivery capability",
      sections: [
        { title: "Customs and EAEU compliance", text: "Before departure we review the commodity, use, material, model, HS code, declaration elements, contract, invoice, packing documents, certificates and origin files; after departure we coordinate export, import, transit, amendments and inspection.", bullets: ["HS classification", "Cargo-file consistency", "EAEU certificates", "Border exception coordination"] },
        { title: "Cross-border TIR fleet service", text: "Group Volvo and Scania resources, an industry-leading 182-unit fleet and 5 Sitrak cage trucks in Kazakhstan support China-Kazakhstan-Europe road transport.", bullets: ["TIR road", "Volvo/Scania", "182-unit fleet", "Sitrak cage trucks"] },
        { title: "China outbound services", text: "For Chinese companies entering Kazakhstan and Europe, we coordinate logistics, customs, warehousing, local delivery and operating setup.", bullets: ["Outbound logistics", "Local fulfillment", "Customs compliance", "Warehouse delivery"] },
        { title: "Kuryk Green Channel", text: "Schedule, port coordination, loading windows and exception alerts around the Trans-Caspian node.", bullets: ["Port schedule", "Capacity coordination", "Node alerts", "Arrival review"] },
        { title: "Warehousing", text: "Almaty fulfillment, labeling, sorting, light processing, inventory counting and reverse logistics.", bullets: ["SKU stock", "Labeling", "Returns", "Variance report"] },
      ],
      panelsTitle: "Customs responsibility chain",
      panels: [
        { label: "Customs", title: "Compliance first, transit promise second", text: "Incomplete files make later promises unreliable. We do not promise ‘guaranteed clearance’; we move foreseeable issues upstream and name the owner of border issues.", points: ["Trade-file review", "Certificates and controls", "Taxes and declaration data", "Customs milestone updates"] },
        { label: "TIR", title: "Cross-border TIR as schedulable capacity", text: "Not ad-hoc truck sourcing, but road capacity planned through Group fleet resources and Kazakhstan local vehicles.", points: ["Volvo/Scania linehaul", "182-unit fleet", "5 Sitrak cage trucks", "TIR node coordination"] },
        { label: "Outbound", title: "Helping Chinese companies enter KZ and Europe", text: "From the first shipment to local fulfillment, logistics, customs and delivery capability are built into the market entry plan.", points: ["Route diagnosis", "Customs compliance", "Local warehousing", "Delivery review"] },
        { label: "Warehouse", title: "Inventory belongs in the operations ledger", text: "Warehousing is part of delivery rhythm, not static space.", points: ["Inbound QC", "Batch/SKU", "Pick and pack", "Returns"] },
        { label: "Linehaul", title: "Multimodal transport lowers single-route exposure", text: "Rail, road, sea and air are combined by cargo and time.", points: ["Rail", "TIR road", "Caspian sea", "Air fallback"] },
      ],
      timelineTitle: "Customs sequence for one shipment",
      timeline: [
        { step: "01", title: "Identify cargo", text: "Define commodity, use, material, model, regulatory attributes and trade terms." },
        { step: "02", title: "Close the file", text: "Check HS code, declaration data, invoice, packing list, certificates and origin documents." },
        { step: "03", title: "Connect the border", text: "Update export, import, transit, amendment and inspection milestones." },
        { step: "04", title: "Release and archive", text: "Retain key files, milestone results and exception records for review." },
      ],
      ctaTitle: "Put the cargo, files and certificates on the table",
      ctaText: "Send the commodity, use, material, trade terms, origin/destination and available files. We will identify customs requirements and gaps before configuring transport.",
      ctaButton: "Ask about customs and transport",
    },
    ru: {
      metaTitle: "Таможня и трансграничная логистика | HPF.kz",
      metaDescription: "HPF.kz координирует экспорт из Китая, импорт в Казахстан и транзит: код ТН ВЭД, проверка файлов, сертификаты ЕАЭС, досмотр, TIR, склад и местная доставка.",
      kicker: "Таможня и трансграничные операции",
      title: "Сначала таможня. Затем перевозка.",
      lead: "Начинаем с идентификации груза, кода ТН ВЭД и проверки торговых файлов, связываем экспорт из Китая, импорт в Казахстан и транзит, затем включаем транспорт, склад и доставку в единую цепочку ответственности.",
      primaryAction: "Отправить потребность",
      secondaryAction: "Маршруты",
      visualLabel: "Таможня и операции",
      stats: [
        { value: "182", label: "единицы парка группы" },
        { value: "V+S", label: "Volvo/Scania парк" },
        { value: "5", label: "Sitrak фургоны KZ" },
        { value: "TIR", label: "автодорожный продукт" },
      ],
      sectionsTitle: "Таможня и исполнение",
      sections: [
        { title: "Таможня и соответствие ЕАЭС", text: "До отправки проверяем товар, назначение, материал, модель, код ТН ВЭД, сведения декларации, контракт, инвойс, упаковочные документы, сертификаты и происхождение; после отправки координируем экспорт, импорт, транзит, корректировки и досмотр.", bullets: ["Код ТН ВЭД", "Согласованность файлов", "Сертификаты ЕАЭС", "Пограничные отклонения"] },
        { title: "Трансграничный TIR парк", text: "Ресурсы группы Volvo и Scania, 182 единицы парка первого эшелона отрасли и 5 фургонов Sitrak в Казахстане поддерживают автоперевозки Китай-Казахстан-Европа.", bullets: ["TIR авто", "Volvo/Scania", "182 единицы", "Sitrak фургоны"] },
        { title: "Сервис выхода китайских компаний", text: "Для китайских компаний, выходящих в Казахстан и Европу, мы координируем логистику, таможню, склад, местную доставку и операционный запуск.", bullets: ["Выход на рынок", "Локальное исполнение", "Таможня", "Склад-доставка"] },
        { title: "Зеленый канал Курык", text: "Расписание, портовая координация, окна погрузки и предупреждения.", bullets: ["Порт", "Емкость", "Предупреждения", "Анализ"] },
        { title: "Склад", text: "Алматы, маркировка, сортировка, легкая обработка, инвентаризация и возвраты.", bullets: ["SKU", "Маркировка", "Возвраты", "Отчет"] },
      ],
      panelsTitle: "Цепочка ответственности таможни",
      panels: [
        { label: "Таможня", title: "Сначала комплаенс", text: "Неполные документы делают сроки ненадёжными. Мы не обещаем «гарантированное оформление»: предсказуемые вопросы решаем заранее, а пограничные закрепляем за ответственным.", points: ["Проверка торговых файлов", "Сертификаты и требования", "Налоги и данные декларации", "Статусы оформления"] },
        { label: "TIR", title: "TIR как планируемая мощность", text: "Не разовый поиск машины, а автоплечо, планируемое через ресурсы группы и локальный парк Казахстана.", points: ["Volvo/Scania", "182 единицы", "5 Sitrak фургонов", "TIR узлы"] },
        { label: "Выход", title: "Помогаем китайским компаниям выйти в KZ и Европу", text: "От первой партии до локального исполнения: логистика, таможня и доставка становятся частью плана выхода.", points: ["Маршрут", "Таможня", "Локальный склад", "Отчет"] },
        { label: "Склад", title: "Склад в операционном журнале", text: "Склад является частью ритма доставки.", points: ["Приемка", "Партия/SKU", "Комплектация", "Возвраты"] },
        { label: "Магистраль", title: "Мультимодальность снижает риск", text: "ЖД, авто, море и авиа комбинируются по грузу и сроку.", points: ["ЖД", "TIR", "Каспий", "Авиа"] },
      ],
      timelineTitle: "Порядок таможенной работы одной перевозки",
      timeline: [
        { step: "01", title: "Идентификация груза", text: "Товар, назначение, материал, модель, регуляторные свойства и условия торговли." },
        { step: "02", title: "Закрытие файлов", text: "Код ТН ВЭД, сведения декларации, инвойс, упаковочный лист, сертификаты и происхождение." },
        { step: "03", title: "Связь с границей", text: "Статусы экспорта, импорта, транзита, корректировки и досмотра." },
        { step: "04", title: "Выпуск и архив", text: "Ключевые файлы, результаты этапов и отклонения сохраняются для разбора." },
      ],
      ctaTitle: "Положим груз, файлы и сертификаты на стол",
      ctaText: "Отправьте товар, назначение, материал, условия торговли, маршрут и имеющиеся файлы. Сначала определим таможенные требования и пробелы, затем настроим перевозку.",
      ctaButton: "Спросить о таможне и перевозке",
    },
  },
  routes: {
    image: railImage,
    imageAlt: { zh: "铁路与干线物流路线", en: "Rail and linehaul logistics route", ru: "Железнодорожный маршрут" },
    zh: {
      metaTitle: "路线网络 | HPF.kz",
      metaDescription: "HPF.kz 设计中国、哈萨克斯坦、库雷克港、巴库、格鲁吉亚、土耳其和欧洲方向的多式联运路线。",
      kicker: "Route network",
      title: "中哈欧路线网络",
      lead: "路线设计不止是地图展示，而是容量、时效、合规、转关和收货预约的综合承诺。",
      primaryAction: "配置路线",
      secondaryAction: "查看平台",
      visualLabel: "Middle Corridor",
      stats: [
        { value: "CN", label: "中国集货" },
        { value: "KZ", label: "阿拉木图枢纽" },
        { value: "Kuryk", label: "跨里海节点" },
        { value: "EU", label: "欧洲交付" },
      ],
      sectionsTitle: "路线分段",
      sections: [
        { title: "中国至阿拉木图", text: "工厂提货、出口文件、集拼与铁路/公路入境安排。", bullets: ["工厂提货", "出口文件", "集拼", "入境预约"] },
        { title: "阿拉木图至库雷克", text: "按货类、时效和港口窗口切换铁路、公路和短驳方案。", bullets: ["铁路", "公路", "短驳", "窗口排期"] },
        { title: "库雷克至欧洲", text: "经巴库、格鲁吉亚、土耳其或欧洲收货端完成转关和末端交付。", bullets: ["巴库", "格鲁吉亚", "土耳其", "欧洲预约"] },
      ],
      panelsTitle: "路线方案切换",
      panels: [
        { label: "标准线", title: "成本与时效平衡", text: "适合常规贸易货、稳定补货和计划性订单。", points: ["铁路/公路组合", "固定节点", "常规清关", "POD 留痕"] },
        { label: "加急线", title: "以关键节点优先级换时效", text: "适合备件、项目节点和高价值 SKU。", points: ["优先取货", "快速文件预审", "空运/公路备选", "异常升级"] },
        { label: "项目线", title: "为超限和工程货定制", text: "适合设备、工程机械和大件项目物流。", points: ["许可前置", "吊装计划", "路径勘验", "现场交付"] },
      ],
      timelineTitle: "中间走廊执行节点",
      timeline: [
        { step: "CN", title: "中国集货", text: "取货、集拼、出口文件和装车。" },
        { step: "KZ", title: "哈萨克斯坦入境", text: "入境清关、枢纽分拨和干线切换。" },
        { step: "SEA", title: "跨里海", text: "库雷克排期、装船、巴库到港。" },
        { step: "EU", title: "欧洲交付", text: "转关、预约、签收和回单。" },
      ],
      ctaTitle: "先设计路线，再承诺价格",
      ctaText: "路线边界清楚，报价才有意义。",
      ctaButton: "获取路线建议",
    },
    en: {
      metaTitle: "Routes | HPF.kz",
      metaDescription: "HPF.kz designs multimodal routes across China, Kazakhstan, Kuryk, Baku, Georgia, Turkey and Europe.",
      kicker: "Route network",
      title: "China-Kazakhstan-Europe route network",
      lead: "Route design is not a map graphic. It is a combined promise across capacity, transit time, compliance, transit customs and consignee appointment.",
      primaryAction: "Configure route",
      secondaryAction: "View platform",
      visualLabel: "Middle Corridor",
      stats: [
        { value: "CN", label: "China origin" },
        { value: "KZ", label: "Almaty hub" },
        { value: "Kuryk", label: "Caspian node" },
        { value: "EU", label: "Europe delivery" },
      ],
      sectionsTitle: "Route legs",
      sections: [
        { title: "China to Almaty", text: "Factory pickup, export files, consolidation and rail/road import planning.", bullets: ["Pickup", "Export files", "Consolidation", "Import appointment"] },
        { title: "Almaty to Kuryk", text: "Rail, road and drayage are switched by cargo, time and port window.", bullets: ["Rail", "Road", "Drayage", "Port window"] },
        { title: "Kuryk to Europe", text: "Transit customs and final delivery through Baku, Georgia, Turkey or European consignee side.", bullets: ["Baku", "Georgia", "Turkey", "Europe appointment"] },
      ],
      panelsTitle: "Switch route plans",
      panels: [
        { label: "Standard", title: "Cost and time balance", text: "For regular trade cargo, replenishment and planned orders.", points: ["Rail/road mix", "Fixed nodes", "Normal customs", "POD trail"] },
        { label: "Priority", title: "Time gained through node priority", text: "For spare parts, project milestones and high-value SKUs.", points: ["Priority pickup", "Fast file review", "Air/road fallback", "Exception escalation"] },
        { label: "Project", title: "For oversized and equipment cargo", text: "For machinery, equipment and project logistics.", points: ["Permits first", "Lifting plan", "Route survey", "Site delivery"] },
      ],
      timelineTitle: "Middle Corridor milestones",
      timeline: [
        { step: "CN", title: "China origin", text: "Pickup, consolidation, export files and loading." },
        { step: "KZ", title: "Kazakhstan import", text: "Import clearance, hub distribution and linehaul switch." },
        { step: "SEA", title: "Trans-Caspian", text: "Kuryk schedule, loading and Baku arrival." },
        { step: "EU", title: "Europe delivery", text: "Transit customs, appointment, POD and review." },
      ],
      ctaTitle: "Design the route before promising the rate",
      ctaText: "A rate only matters when route boundaries are clear.",
      ctaButton: "Get route advice",
    },
    ru: {
      metaTitle: "Маршруты | HPF.kz",
      metaDescription: "HPF.kz проектирует мультимодальные маршруты Китай, Казахстан, Курык, Баку, Грузия, Турция и Европа.",
      kicker: "Сеть маршрутов",
      title: "Маршрутная сеть Китай-Казахстан-Европа",
      lead: "Маршрут - это не карта, а обещание по емкости, сроку, комплаенсу, транзиту и записи получателя.",
      primaryAction: "Настроить маршрут",
      secondaryAction: "Платформа",
      visualLabel: "Средний коридор",
      stats: [
        { value: "CN", label: "Китай" },
        { value: "KZ", label: "Алматы" },
        { value: "Kuryk", label: "Каспий" },
        { value: "EU", label: "Европа" },
      ],
      sectionsTitle: "Этапы маршрута",
      sections: [
        { title: "Китай - Алматы", text: "Забор, экспортные документы, консолидация и планирование ЖД/авто.", bullets: ["Забор", "Экспорт", "Консолидация", "Импорт"] },
        { title: "Алматы - Курык", text: "ЖД, авто и короткая доставка переключаются по грузу, сроку и окну порта.", bullets: ["ЖД", "Авто", "Подвоз", "Порт"] },
        { title: "Курык - Европа", text: "Транзит и доставка через Баку, Грузию, Турцию или сторону получателя.", bullets: ["Баку", "Грузия", "Турция", "Европа"] },
      ],
      panelsTitle: "Варианты маршрута",
      panels: [
        { label: "Стандарт", title: "Баланс цены и срока", text: "Для регулярных грузов и плановых заказов.", points: ["ЖД/авто", "Узлы", "Таможня", "POD"] },
        { label: "Срочно", title: "Приоритет узлов ради срока", text: "Для запчастей, проектных этапов и ценных SKU.", points: ["Приоритет", "Проверка", "Авиа/авто", "Эскалация"] },
        { label: "Проект", title: "Для негабарита и техники", text: "Для оборудования и проектной логистики.", points: ["Разрешения", "Погрузка", "Маршрут", "Площадка"] },
      ],
      timelineTitle: "Узлы Среднего коридора",
      timeline: [
        { step: "CN", title: "Китай", text: "Забор, консолидация, экспорт и загрузка." },
        { step: "KZ", title: "Казахстан", text: "Импорт, хаб и смена магистрали." },
        { step: "SEA", title: "Каспий", text: "Курык, погрузка и Баку." },
        { step: "EU", title: "Европа", text: "Транзит, запись, POD и анализ." },
      ],
      ctaTitle: "Сначала маршрут, потом ставка",
      ctaText: "Ставка имеет смысл, когда ясны границы маршрута.",
      ctaButton: "Получить маршрут",
    },
  },
  industries: {
    image: warehouseImage,
    imageAlt: { zh: "行业货物分拨场景", en: "Industry cargo distribution", ru: "Отраслевая дистрибуция" },
    zh: {
      metaTitle: "行业方案 | HPF.kz",
      metaDescription: "HPF.kz 面向工程机械、汽车零配件、跨境电商、矿产能源和快消零售提供行业物流方案。",
      kicker: "Industry playbooks",
      title: "按货类设计，而不是按模板报价",
      lead: "不同行业的风险不一样。工程机械、汽车零配件、电商 SKU、矿产能源和快消零售需要不同的路线、文件和节点控制。",
      primaryAction: "选择行业方案",
      secondaryAction: "查看服务",
      visualLabel: "Cargo-specific planning",
      stats: [
        { value: "5类", label: "重点行业" },
        { value: "VIN", label: "汽车批次管理" },
        { value: "SKU", label: "电商库存管理" },
        { value: "Permit", label: "工程许可前置" },
      ],
      sectionsTitle: "重点行业",
      sections: [
        { title: "工程机械", text: "超限许可、吊装计划、路径勘验和项目节点交付。", bullets: ["许可", "吊装", "路径", "工地"] },
        { title: "汽车零配件", text: "VIN/批次管理、备件补给、CKD/SKD 和售后网络补货。", bullets: ["VIN", "批次", "CKD/SKD", "备件"] },
        { title: "跨境电商", text: "中高价值 SKU 的库存可视化、平台对接、退换逆向闭环。", bullets: ["SKU", "平台", "退换", "签收"] },
      ],
      panelsTitle: "行业方案切换",
      panels: [
        { label: "工程机械", title: "项目节点优先", text: "设备晚到会影响施工节点，路线必须反推项目计划。", points: ["许可前置", "吊装窗口", "场地交接", "异常升级"] },
        { label: "汽车", title: "批次可追溯优先", text: "零配件不是普通箱货，批次和售后补给必须可追踪。", points: ["VIN/批次", "备件池", "CKD/SKD", "经销网络"] },
        { label: "电商", title: "库存周转优先", text: "电商核心不是运输一次，而是稳定补货和逆向处理。", points: ["SKU", "入库", "分拣", "退换"] },
      ],
      timelineTitle: "行业方案形成流程",
      timeline: [
        { step: "01", title: "货类约束", text: "确认尺寸、价值、证书、温控和危险属性。" },
        { step: "02", title: "节点设计", text: "按行业风险配置路线和仓配节点。" },
        { step: "03", title: "执行标准", text: "设定签收、异常、文件和报告标准。" },
        { step: "04", title: "模板复用", text: "沉淀为下一批货可复用的行业模板。" },
      ],
      ctaTitle: "让方案从货类开始",
      ctaText: "行业信息越准确，路线和价格越可靠。",
      ctaButton: "提交行业需求",
    },
    en: {
      metaTitle: "Industries | HPF.kz",
      metaDescription: "HPF.kz provides industry logistics playbooks for machinery, automotive parts, e-commerce, mining, energy and retail.",
      kicker: "Industry playbooks",
      title: "Plan by cargo reality, not by generic rates",
      lead: "Each industry has different risk. Machinery, auto parts, e-commerce SKUs, mining, energy and retail require different routes, documents and node controls.",
      primaryAction: "Choose industry plan",
      secondaryAction: "View services",
      visualLabel: "Cargo-specific planning",
      stats: [
        { value: "5", label: "focus industries" },
        { value: "VIN", label: "auto batch control" },
        { value: "SKU", label: "e-commerce stock" },
        { value: "Permit", label: "project permits" },
      ],
      sectionsTitle: "Focus industries",
      sections: [
        { title: "Machinery", text: "Oversized permits, lifting plan, route survey and project-site delivery.", bullets: ["Permits", "Lifting", "Route", "Site"] },
        { title: "Automotive parts", text: "VIN/batch control, spare parts, CKD/SKD and dealer replenishment.", bullets: ["VIN", "Batch", "CKD/SKD", "Parts"] },
        { title: "E-commerce", text: "SKU visibility, marketplace integration and closed-loop returns for medium and high-value goods.", bullets: ["SKU", "Platform", "Returns", "POD"] },
      ],
      panelsTitle: "Switch industry plans",
      panels: [
        { label: "Machinery", title: "Project milestones first", text: "Late equipment affects site progress, so routing works backward from the project plan.", points: ["Permits", "Lifting window", "Site handover", "Escalation"] },
        { label: "Auto", title: "Batch traceability first", text: "Parts require batch and aftersales replenishment visibility.", points: ["VIN/batch", "Parts pool", "CKD/SKD", "Dealer network"] },
        { label: "E-commerce", title: "Inventory rotation first", text: "The core is not one shipment, but stable replenishment and reverse logistics.", points: ["SKU", "Inbound", "Sorting", "Returns"] },
      ],
      timelineTitle: "How an industry plan is built",
      timeline: [
        { step: "01", title: "Cargo constraints", text: "Size, value, certificates, temperature and regulated attributes." },
        { step: "02", title: "Node design", text: "Route and warehouse nodes by industry risk." },
        { step: "03", title: "Execution standard", text: "POD, exception, document and report standards." },
        { step: "04", title: "Template reuse", text: "Reusable industry playbook for the next batch." },
      ],
      ctaTitle: "Start planning from cargo reality",
      ctaText: "Better industry information makes route and rate more reliable.",
      ctaButton: "Submit industry need",
    },
    ru: {
      metaTitle: "Отрасли | HPF.kz",
      metaDescription: "HPF.kz предлагает отраслевые логистические сценарии для техники, автозапчастей, e-commerce, сырья, энергетики и ритейла.",
      kicker: "Отраслевые сценарии",
      title: "План по реальности груза, а не по общей ставке",
      lead: "У каждой отрасли свой риск. Техника, автозапчасти, e-commerce SKU, сырье и ритейл требуют разных маршрутов и документов.",
      primaryAction: "Выбрать отрасль",
      secondaryAction: "Сервисы",
      visualLabel: "Планирование по грузу",
      stats: [
        { value: "5", label: "отраслей" },
        { value: "VIN", label: "партии авто" },
        { value: "SKU", label: "e-commerce" },
        { value: "Permit", label: "разрешения" },
      ],
      sectionsTitle: "Отрасли",
      sections: [
        { title: "Техника", text: "Разрешения, погрузка, проверка маршрута и доставка на объект.", bullets: ["Разрешения", "Погрузка", "Маршрут", "Объект"] },
        { title: "Автозапчасти", text: "VIN/партии, запасные части, CKD/SKD и дилерское пополнение.", bullets: ["VIN", "Партия", "CKD/SKD", "Запчасти"] },
        { title: "E-commerce", text: "SKU-видимость, интеграция платформ и возвраты.", bullets: ["SKU", "Платформа", "Возвраты", "POD"] },
      ],
      panelsTitle: "Сценарии отраслей",
      panels: [
        { label: "Техника", title: "Сначала этап проекта", text: "Задержка техники влияет на стройку, маршрут строится от плана проекта.", points: ["Разрешения", "Окно погрузки", "Передача", "Эскалация"] },
        { label: "Авто", title: "Сначала прослеживаемость", text: "Запчастям нужны партии и видимость пополнения.", points: ["VIN/партия", "Пул запчастей", "CKD/SKD", "Дилеры"] },
        { label: "E-commerce", title: "Сначала оборот склада", text: "Главное - не одна перевозка, а стабильное пополнение и возвраты.", points: ["SKU", "Приемка", "Сортировка", "Возвраты"] },
      ],
      timelineTitle: "Формирование сценария",
      timeline: [
        { step: "01", title: "Ограничения", text: "Размер, стоимость, сертификаты, температура и регуляторика." },
        { step: "02", title: "Узлы", text: "Маршрут и склад по рискам отрасли." },
        { step: "03", title: "Стандарт", text: "POD, исключения, документы и отчеты." },
        { step: "04", title: "Шаблон", text: "Повторное использование для следующей партии." },
      ],
      ctaTitle: "Начнем с реальности груза",
      ctaText: "Чем точнее отраслевые данные, тем надежнее маршрут и ставка.",
      ctaButton: "Отправить запрос",
    },
  },
  platform: {
    image: routeImage,
    imageAlt: { zh: "物流平台数据看板", en: "Logistics platform dashboard", ru: "Панель логистики" },
    zh: {
      metaTitle: "平台能力 | HPF.kz",
      metaDescription: "HPF.kz 平台能力覆盖路线报价、文件中台、节点追踪、库存状态、异常处理和运营复盘。",
      kicker: "Operating platform",
      title: "让物流状态进入同一张运营台账",
      lead: "平台不是把地图放上网页，而是把报价、文件、库存、节点、异常和复盘报告放进同一套工作流。",
      primaryAction: "体验平台能力",
      secondaryAction: "查看服务",
      visualLabel: "Control ledger",
      stats: [
        { value: "6类", label: "运营数据" },
        { value: "ETA", label: "预计到达" },
        { value: "Docs", label: "文件留痕" },
        { value: "KPI", label: "复盘指标" },
      ],
      sectionsTitle: "平台模块",
      sections: [
        { title: "路线报价", text: "按时效、风险、成本输出多方案对比，而不是单行报价。", bullets: ["成本", "时效", "风险", "备选"] },
        { title: "文件中台", text: "报关资料、证书、提单、POD 和异常说明统一留痕。", bullets: ["报关", "证书", "提单", "POD"] },
        { title: "节点追踪", text: "每个关键节点显示状态、责任方、预计到达和异常原因。", bullets: ["状态", "责任", "ETA", "异常"] },
      ],
      panelsTitle: "平台视图切换",
      panels: [
        { label: "报价", title: "多方案对比", text: "客户看到的不只是价格，还有价格背后的时效和风险。", points: ["标准线", "加急线", "项目线", "成本差异"] },
        { label: "文件", title: "文件完整性管理", text: "文件缺口在运输前暴露，减少清关阶段返工。", points: ["缺失提示", "版本记录", "证书到期", "签收归档"] },
        { label: "复盘", title: "每票货形成经营数据", text: "时效、异常、费用偏差进入下一票货的决策。", points: ["准时率", "异常类型", "成本偏差", "客户反馈"] },
      ],
      timelineTitle: "平台工作流",
      timeline: [
        { step: "01", title: "报价建模", text: "路线、费用、风险和备选方案。" },
        { step: "02", title: "文件收口", text: "运输前校验清关资料和证书。" },
        { step: "03", title: "节点执行", text: "跟踪状态、ETA 和异常。" },
        { step: "04", title: "复盘沉淀", text: "转化为下一次决策数据。" },
      ],
      ctaTitle: "减少追问，增加可见性",
      ctaText: "平台能力的目标是让客户少问状态，团队少靠记忆。",
      ctaButton: "了解平台",
    },
    en: {
      metaTitle: "Platform | HPF.kz",
      metaDescription: "HPF.kz platform capabilities cover route quotation, document center, milestone tracking, inventory status, exceptions and reviews.",
      kicker: "Operating platform",
      title: "Put logistics status into one operating ledger",
      lead: "The platform is not a map on a webpage. It is one workflow for quotes, documents, inventory, milestones, exceptions and review reports.",
      primaryAction: "Explore platform",
      secondaryAction: "View services",
      visualLabel: "Control ledger",
      stats: [
        { value: "6", label: "data classes" },
        { value: "ETA", label: "arrival estimate" },
        { value: "Docs", label: "document trail" },
        { value: "KPI", label: "review metrics" },
      ],
      sectionsTitle: "Platform modules",
      sections: [
        { title: "Route quotation", text: "Compare time, risk and cost scenarios instead of one-line rates.", bullets: ["Cost", "Time", "Risk", "Fallback"] },
        { title: "Document center", text: "Customs files, certificates, bills, PODs and exception notes stay in one trail.", bullets: ["Customs", "Certificates", "Bills", "POD"] },
        { title: "Milestone tracking", text: "Each key node shows status, owner, ETA and exception reason.", bullets: ["Status", "Owner", "ETA", "Exception"] },
      ],
      panelsTitle: "Switch platform views",
      panels: [
        { label: "Quote", title: "Scenario comparison", text: "Customers see the price and the time/risk behind it.", points: ["Standard", "Priority", "Project", "Cost variance"] },
        { label: "Docs", title: "Document integrity", text: "File gaps are exposed before transport, reducing customs rework.", points: ["Missing files", "Version history", "Certificate expiry", "POD archive"] },
        { label: "Review", title: "Each shipment becomes operating data", text: "Time, exception and cost variance inform the next shipment.", points: ["Punctuality", "Exception type", "Cost variance", "Feedback"] },
      ],
      timelineTitle: "Platform workflow",
      timeline: [
        { step: "01", title: "Quote model", text: "Route, cost, risk and fallback." },
        { step: "02", title: "File close", text: "Customs files and certificates before transport." },
        { step: "03", title: "Node execution", text: "Status, ETA and exception tracking." },
        { step: "04", title: "Review", text: "Data for the next decision." },
      ],
      ctaTitle: "Less follow-up, more visibility",
      ctaText: "The goal is fewer status questions and less reliance on memory.",
      ctaButton: "Discuss platform",
    },
    ru: {
      metaTitle: "Платформа | HPF.kz",
      metaDescription: "Платформа HPF.kz: расчет маршрутов, документы, трекинг, склад, исключения и отчеты.",
      kicker: "Операционная платформа",
      title: "Логистический статус в одном журнале",
      lead: "Платформа - это не карта на сайте, а рабочий процесс для ставок, документов, склада, узлов, исключений и отчетов.",
      primaryAction: "Платформа",
      secondaryAction: "Сервисы",
      visualLabel: "Журнал контроля",
      stats: [
        { value: "6", label: "типов данных" },
        { value: "ETA", label: "прогноз прибытия" },
        { value: "Docs", label: "документы" },
        { value: "KPI", label: "метрики" },
      ],
      sectionsTitle: "Модули платформы",
      sections: [
        { title: "Расчет маршрута", text: "Сравнение срока, риска и стоимости вместо одной ставки.", bullets: ["Цена", "Срок", "Риск", "Резерв"] },
        { title: "Документы", text: "Таможня, сертификаты, накладные, POD и исключения в одном следе.", bullets: ["Таможня", "Сертификаты", "Накладные", "POD"] },
        { title: "Трекинг узлов", text: "Каждый узел показывает статус, владельца, ETA и причину исключения.", bullets: ["Статус", "Владелец", "ETA", "Исключение"] },
      ],
      panelsTitle: "Виды платформы",
      panels: [
        { label: "Ставка", title: "Сравнение сценариев", text: "Клиент видит цену и риски за ней.", points: ["Стандарт", "Срочно", "Проект", "Отклонение"] },
        { label: "Документы", title: "Полнота документов", text: "Пробелы видны до перевозки.", points: ["Недостача", "Версии", "Срок сертификата", "POD"] },
        { label: "Отчет", title: "Каждый груз становится данными", text: "Срок, исключения и стоимость помогают следующей отправке.", points: ["Срок", "Типы", "Стоимость", "Обратная связь"] },
      ],
      timelineTitle: "Рабочий процесс",
      timeline: [
        { step: "01", title: "Модель", text: "Маршрут, стоимость, риск и резерв." },
        { step: "02", title: "Документы", text: "Таможня и сертификаты до перевозки." },
        { step: "03", title: "Узлы", text: "Статус, ETA и исключения." },
        { step: "04", title: "Анализ", text: "Данные для следующего решения." },
      ],
      ctaTitle: "Меньше запросов, больше видимости",
      ctaText: "Цель - меньше вопросов о статусе и меньше зависимости от памяти.",
      ctaButton: "Обсудить платформу",
    },
  },
  about: {
    image: routeImage,
    imageAlt: { zh: "哈萨克斯坦物流枢纽", en: "Kazakhstan logistics hub", ru: "Логистический хаб Казахстана" },
    zh: {
      metaTitle: "关于 HPF.kz",
      metaDescription: "HPF.kz 是位于哈萨克斯坦的跨境物流运营团队，专注中哈欧路线的确定性交付。",
      kicker: "About HPF.kz",
      title: "我们做的不是单票运输，而是可复用的跨境交付能力",
      lead: "HPF.kz 面向中国贸易商、哈萨克斯坦本地客户和欧洲收货方，建立一套可持续、可解释、可复盘的跨境物流运营体系。",
      primaryAction: "联系团队",
      secondaryAction: "查看路线",
      visualLabel: "Almaty based operator",
      stats: [
        { value: "KZ", label: "本地运营基础" },
        { value: "CN/EU", label: "跨境协同" },
        { value: "Compliance", label: "合规先行" },
        { value: "Long-term", label: "长期主义" },
      ],
      sectionsTitle: "我们的原则",
      sections: [
        { title: "确定性优先", text: "不承诺无法控制的结果。先拆解节点和风险，再做交付承诺。", bullets: ["节点", "风险", "边界", "复盘"] },
        { title: "本地能力优先", text: "哈萨克斯坦的口岸、仓储、清关和末端交付需要本地执行力。", bullets: ["阿拉木图", "库雷克", "口岸", "仓配"] },
        { title: "长期复用优先", text: "每一票货都应该沉淀成下一票货更稳定的能力。", bullets: ["模板", "数据", "流程", "经验"] },
      ],
      panelsTitle: "团队能力",
      panels: [
        { label: "运营", title: "把节点推进到底", text: "物流最怕无人负责的灰区，我们把责任边界写进流程。", points: ["节点负责人", "异常升级", "签收闭环", "复盘记录"] },
        { label: "合规", title: "把风险提前到运输前", text: "文件、证书和申报逻辑必须先于运输动作。", points: ["文件预审", "证书清单", "法规提示", "归档"] },
        { label: "客户", title: "让客户看见真实状态", text: "不靠模糊承诺，靠清楚节点和可验证回单。", points: ["ETA", "异常原因", "POD", "报告"] },
      ],
      timelineTitle: "合作方式",
      timeline: [
        { step: "01", title: "需求确认", text: "客户给出货类、路线、时效和贸易条件。" },
        { step: "02", title: "方案共识", text: "双方确认费用、风险、边界和备用方案。" },
        { step: "03", title: "执行协同", text: "按节点同步状态并处理异常。" },
        { step: "04", title: "长期优化", text: "按复盘数据优化下一批货。" },
      ],
      ctaTitle: "让合作从一张路线图开始",
      ctaText: "清楚边界，比漂亮承诺更重要。",
      ctaButton: "联系 HPF.kz",
    },
    en: {
      metaTitle: "About HPF.kz",
      metaDescription: "HPF.kz is a Kazakhstan-based cross-border logistics operator focused on deterministic China-Kazakhstan-Europe delivery.",
      kicker: "About HPF.kz",
      title: "We build reusable cross-border delivery capability",
      lead: "HPF.kz serves Chinese traders, Kazakhstan clients and European consignees with a sustainable, explainable and reviewable operating system.",
      primaryAction: "Contact team",
      secondaryAction: "View routes",
      visualLabel: "Almaty based operator",
      stats: [
        { value: "KZ", label: "local base" },
        { value: "CN/EU", label: "cross-border coordination" },
        { value: "Compliance", label: "compliance first" },
        { value: "Long-term", label: "long-term view" },
      ],
      sectionsTitle: "Operating principles",
      sections: [
        { title: "Certainty first", text: "We do not promise what cannot be controlled. Nodes and risks come before promises.", bullets: ["Nodes", "Risk", "Boundaries", "Review"] },
        { title: "Local capability first", text: "Kazakhstan ports, warehouses, customs and final delivery need local execution.", bullets: ["Almaty", "Kuryk", "Border", "Fulfillment"] },
        { title: "Reusable learning first", text: "Each shipment should make the next shipment more stable.", bullets: ["Templates", "Data", "Process", "Experience"] },
      ],
      panelsTitle: "Team capabilities",
      panels: [
        { label: "Operations", title: "Move every node to closure", text: "Logistics fails in ownerless gaps. We put ownership into the workflow.", points: ["Node owner", "Escalation", "POD closure", "Review record"] },
        { label: "Compliance", title: "Move risk before transport", text: "Files, certificates and declaration logic must precede movement.", points: ["File review", "Certificate list", "Regulation notes", "Archive"] },
        { label: "Customer", title: "Show the real status", text: "Clear nodes and verifiable POD beat vague promises.", points: ["ETA", "Exception reason", "POD", "Report"] },
      ],
      timelineTitle: "How we work",
      timeline: [
        { step: "01", title: "Confirm need", text: "Cargo, route, time and trade terms." },
        { step: "02", title: "Align plan", text: "Cost, risk, boundary and fallback." },
        { step: "03", title: "Execute", text: "Milestone status and exception resolution." },
        { step: "04", title: "Improve", text: "Use review data for the next shipment." },
      ],
      ctaTitle: "Start cooperation from a route map",
      ctaText: "Clear boundaries matter more than polished promises.",
      ctaButton: "Contact HPF.kz",
    },
    ru: {
      metaTitle: "О HPF.kz",
      metaDescription: "HPF.kz - казахстанский оператор трансграничной логистики Китай-Казахстан-Европа.",
      kicker: "О HPF.kz",
      title: "Мы строим повторяемую способность доставки",
      lead: "HPF.kz работает для китайских отправителей, казахстанских клиентов и европейских получателей через понятную операционную систему.",
      primaryAction: "Связаться",
      secondaryAction: "Маршруты",
      visualLabel: "Оператор в Алматы",
      stats: [
        { value: "KZ", label: "локальная база" },
        { value: "CN/EU", label: "координация" },
        { value: "Compliance", label: "комплаенс" },
        { value: "Long-term", label: "долгий горизонт" },
      ],
      sectionsTitle: "Принципы",
      sections: [
        { title: "Сначала определенность", text: "Мы не обещаем то, что нельзя контролировать.", bullets: ["Узлы", "Риск", "Границы", "Анализ"] },
        { title: "Сначала локальная способность", text: "Порты, склады, таможня и доставка в Казахстане требуют локального исполнения.", bullets: ["Алматы", "Курык", "Граница", "Склад"] },
        { title: "Сначала повторяемость", text: "Каждый груз должен делать следующий стабильнее.", bullets: ["Шаблоны", "Данные", "Процесс", "Опыт"] },
      ],
      panelsTitle: "Возможности команды",
      panels: [
        { label: "Операции", title: "Довести каждый узел", text: "Логистика ломается в серых зонах без владельца.", points: ["Владелец", "Эскалация", "POD", "Запись"] },
        { label: "Комплаенс", title: "Риск до перевозки", text: "Документы и логика декларации должны быть до движения.", points: ["Проверка", "Сертификаты", "Регуляторика", "Архив"] },
        { label: "Клиент", title: "Показать реальный статус", text: "Понятные узлы и POD лучше размытых обещаний.", points: ["ETA", "Причина", "POD", "Отчет"] },
      ],
      timelineTitle: "Как мы работаем",
      timeline: [
        { step: "01", title: "Потребность", text: "Груз, маршрут, срок и условия." },
        { step: "02", title: "План", text: "Стоимость, риск, границы и резерв." },
        { step: "03", title: "Исполнение", text: "Статусы и исключения." },
        { step: "04", title: "Улучшение", text: "Данные для следующей отправки." },
      ],
      ctaTitle: "Начнем с маршрутной карты",
      ctaText: "Ясные границы важнее красивых обещаний.",
      ctaButton: "Связаться с HPF.kz",
    },
  },
  contact: {
    image: warehouseImage,
    imageAlt: { zh: "物流需求沟通", en: "Logistics request discussion", ru: "Запрос логистики" },
    zh: {
      metaTitle: "联系 | HPF.kz",
      metaDescription: "联系 HPF.kz 获取中哈欧跨境物流路线、清关、仓储、干线和平台方案。",
      kicker: "Route request",
      title: "提交一票货，我们返回一张可执行路线图",
      lead: "请尽量提供货类、起运地、目的地、重量体积、贸易条款和期望到达时间。信息越完整，方案越准确。",
      primaryAction: "发送邮件",
      secondaryAction: "查看服务",
      visualLabel: "bd@hpf.kz",
      stats: [
        { value: "24h", label: "需求响应目标" },
        { value: "4项", label: "基础信息" },
        { value: "3语", label: "沟通语言" },
        { value: "1图", label: "路线建议" },
      ],
      sectionsTitle: "请提供这些信息",
      sections: [
        { title: "货物信息", text: "货类、品名、重量、体积、包装、是否危险品或温控。", bullets: ["货类", "重量", "体积", "包装"] },
        { title: "路线信息", text: "起运地、目的地、收货方、期望到达时间和可接受备选路线。", bullets: ["起运地", "目的地", "时效", "备选"] },
        { title: "贸易信息", text: "贸易条款、发票、箱单、证书和清关资料现状。", bullets: ["Incoterms", "发票", "箱单", "证书"] },
      ],
      panelsTitle: "咨询类型",
      panels: [
        { label: "新路线", title: "第一次走中哈欧路线", text: "重点确认货类、合规和收货端要求。", points: ["路线设计", "风险边界", "费用估算", "执行周期"] },
        { label: "已有货", title: "正在运输或准备发货", text: "重点确认当前节点、文件状态和异常风险。", points: ["节点诊断", "文件补齐", "异常处理", "到达预测"] },
        { label: "长期合作", title: "稳定批量或项目物流", text: "重点建立模板、SLA 和复盘机制。", points: ["行业模板", "仓配配置", "KPI", "月度复盘"] },
      ],
      timelineTitle: "响应流程",
      timeline: [
        { step: "01", title: "发送需求", text: "邮件或表单提交基础信息。" },
        { step: "02", title: "补齐资料", text: "确认缺失文件和关键约束。" },
        { step: "03", title: "输出方案", text: "返回路线、费用区间、风险和下一步。" },
        { step: "04", title: "确认执行", text: "锁定节点、责任方和沟通机制。" },
      ],
      ctaTitle: "商务合作邮箱",
      ctaText: "bd@hpf.kz / contact@hpf.kz",
      ctaButton: "发送邮件",
    },
    en: {
      metaTitle: "Contact | HPF.kz",
      metaDescription: "Contact HPF.kz for China-Kazakhstan-Europe logistics routes, customs, warehousing, linehaul and platform plans.",
      kicker: "Route request",
      title: "Send one shipment. Receive an executable route map.",
      lead: "Please provide cargo type, origin, destination, weight/volume, trade terms and target arrival. Better input produces a better plan.",
      primaryAction: "Send email",
      secondaryAction: "View services",
      visualLabel: "bd@hpf.kz",
      stats: [
        { value: "24h", label: "response target" },
        { value: "4", label: "basic inputs" },
        { value: "3 langs", label: "communication" },
        { value: "1 map", label: "route advice" },
      ],
      sectionsTitle: "Information to provide",
      sections: [
        { title: "Cargo", text: "Cargo type, commodity, weight, volume, package, dangerous or temperature-controlled attributes.", bullets: ["Type", "Weight", "Volume", "Package"] },
        { title: "Route", text: "Origin, destination, consignee, target arrival and acceptable fallback routes.", bullets: ["Origin", "Destination", "Time", "Fallback"] },
        { title: "Trade", text: "Trade terms, invoice, packing list, certificates and customs file status.", bullets: ["Incoterms", "Invoice", "Packing list", "Certificates"] },
      ],
      panelsTitle: "Request types",
      panels: [
        { label: "New route", title: "First China-Kazakhstan-Europe shipment", text: "Focus on cargo, compliance and consignee requirements.", points: ["Route design", "Risk boundary", "Cost estimate", "Execution cycle"] },
        { label: "Active cargo", title: "In transit or ready to ship", text: "Focus on current node, file status and exception risk.", points: ["Node diagnosis", "File completion", "Exception handling", "ETA"] },
        { label: "Long-term", title: "Stable batch or project logistics", text: "Focus on templates, SLA and review rhythm.", points: ["Industry template", "Warehouse setup", "KPI", "Monthly review"] },
      ],
      timelineTitle: "Response workflow",
      timeline: [
        { step: "01", title: "Send request", text: "Submit basic information by email or form." },
        { step: "02", title: "Complete files", text: "Confirm missing files and constraints." },
        { step: "03", title: "Plan", text: "Route, cost range, risk and next step." },
        { step: "04", title: "Execute", text: "Lock nodes, owners and communication rhythm." },
      ],
      ctaTitle: "Business development email",
      ctaText: "bd@hpf.kz / contact@hpf.kz",
      ctaButton: "Send email",
    },
    ru: {
      metaTitle: "Контакты | HPF.kz",
      metaDescription: "Свяжитесь с HPF.kz по маршрутам Китай-Казахстан-Европа, таможне, складу и платформе.",
      kicker: "Запрос маршрута",
      title: "Отправьте груз. Получите исполнимую карту маршрута.",
      lead: "Укажите тип груза, отправление, назначение, вес/объем, условия и желаемый срок.",
      primaryAction: "Написать",
      secondaryAction: "Сервисы",
      visualLabel: "bd@hpf.kz",
      stats: [
        { value: "24h", label: "цель ответа" },
        { value: "4", label: "базовых данных" },
        { value: "3 языка", label: "коммуникация" },
        { value: "1 карта", label: "маршрут" },
      ],
      sectionsTitle: "Какие данные нужны",
      sections: [
        { title: "Груз", text: "Тип, наименование, вес, объем, упаковка, опасность или температура.", bullets: ["Тип", "Вес", "Объем", "Упаковка"] },
        { title: "Маршрут", text: "Отправление, назначение, получатель, срок и резервные варианты.", bullets: ["Отправление", "Назначение", "Срок", "Резерв"] },
        { title: "Торговля", text: "Условия, инвойс, упаковочный лист, сертификаты и таможенные файлы.", bullets: ["Incoterms", "Инвойс", "Лист", "Сертификаты"] },
      ],
      panelsTitle: "Тип запроса",
      panels: [
        { label: "Новый", title: "Первая отправка", text: "Фокус на груз, комплаенс и получателя.", points: ["Маршрут", "Риск", "Стоимость", "Цикл"] },
        { label: "Активный", title: "Груз в работе", text: "Фокус на текущий узел, документы и риск.", points: ["Диагностика", "Документы", "Исключения", "ETA"] },
        { label: "Долгий", title: "Партии или проект", text: "Фокус на шаблоны, SLA и ритм анализа.", points: ["Шаблон", "Склад", "KPI", "Анализ"] },
      ],
      timelineTitle: "Процесс ответа",
      timeline: [
        { step: "01", title: "Запрос", text: "Базовая информация по email или форме." },
        { step: "02", title: "Файлы", text: "Недостающие документы и ограничения." },
        { step: "03", title: "План", text: "Маршрут, стоимость, риск и следующий шаг." },
        { step: "04", title: "Исполнение", text: "Узлы, владельцы и ритм связи." },
      ],
      ctaTitle: "Email для сотрудничества",
      ctaText: "bd@hpf.kz / contact@hpf.kz",
      ctaButton: "Написать",
    },
  },
};
